// Lista estática de empresas conocidas para el autocompletado del
// buscador. No requiere ninguna API ni clave — es solo una lista de
// referencia de nombre + ticker para facilitar añadir empresas.
window.KNOWN_COMPANIES = [
  { name: "Apple", ticker: "AAPL" },
  { name: "Microsoft", ticker: "MSFT" },
  { name: "Alphabet (Google)", ticker: "GOOGL" },
  { name: "Amazon", ticker: "AMZN" },
  { name: "NVIDIA", ticker: "NVDA" },
  { name: "Meta Platforms", ticker: "META" },
  { name: "Tesla", ticker: "TSLA" },
  { name: "Berkshire Hathaway", ticker: "BRK.B" },
  { name: "Broadcom", ticker: "AVGO" },
  { name: "Eli Lilly", ticker: "LLY" },
  { name: "Visa", ticker: "V" },
  { name: "Mastercard", ticker: "MA" },
  { name: "JPMorgan Chase", ticker: "JPM" },
  { name: "Walmart", ticker: "WMT" },
  { name: "UnitedHealth", ticker: "UNH" },
  { name: "Exxon Mobil", ticker: "XOM" },
  { name: "Johnson & Johnson", ticker: "JNJ" },
  { name: "Procter & Gamble", ticker: "PG" },
  { name: "Oracle", ticker: "ORCL" },
  { name: "Home Depot", ticker: "HD" },
  { name: "Costco", ticker: "COST" },
  { name: "Netflix", ticker: "NFLX" },
  { name: "Coca-Cola", ticker: "KO" },
  { name: "PepsiCo", ticker: "PEP" },
  { name: "Chevron", ticker: "CVX" },
  { name: "AbbVie", ticker: "ABBV" },
  { name: "Bank of America", ticker: "BAC" },
  { name: "Salesforce", ticker: "CRM" },
  { name: "AMD", ticker: "AMD" },
  { name: "Adobe", ticker: "ADBE" },
  { name: "Intel", ticker: "INTC" },
  { name: "Qualcomm", ticker: "QCOM" },
  { name: "Cisco", ticker: "CSCO" },
  { name: "McDonald's", ticker: "MCD" },
  { name: "Nike", ticker: "NKE" },
  { name: "Disney", ticker: "DIS" },
  { name: "Verizon", ticker: "VZ" },
  { name: "AT&T", ticker: "T" },
  { name: "Comcast", ticker: "CMCSA" },
  { name: "PayPal", ticker: "PYPL" },
  { name: "IBM", ticker: "IBM" },
  { name: "Uber", ticker: "UBER" },
  { name: "Starbucks", ticker: "SBUX" },
  { name: "Goldman Sachs", ticker: "GS" },
  { name: "Morgan Stanley", ticker: "MS" },
  { name: "Boeing", ticker: "BA" },
  { name: "Caterpillar", ticker: "CAT" },
  { name: "Ford Motor", ticker: "F" },
  { name: "General Motors", ticker: "GM" },
  { name: "3M", ticker: "MMM" },
  { name: "Honeywell", ticker: "HON" },
  { name: "FedEx", ticker: "FDX" },
  { name: "UPS", ticker: "UPS" },
  { name: "Airbnb", ticker: "ABNB" },
  { name: "Booking Holdings", ticker: "BKNG" },
  { name: "eBay", ticker: "EBAY" },
  { name: "Spotify", ticker: "SPOT" },
  { name: "Shopify", ticker: "SHOP" },
  { name: "Palantir", ticker: "PLTR" },
  { name: "ServiceNow", ticker: "NOW" },
  { name: "Snowflake", ticker: "SNOW" },
  { name: "Micron Technology", ticker: "MU" },
  { name: "Texas Instruments", ticker: "TXN" },
  { name: "Applied Materials", ticker: "AMAT" },
  { name: "Lam Research", ticker: "LRCX" },
  { name: "ASML", ticker: "ASML" },
  { name: "Taiwan Semiconductor (TSMC)", ticker: "TSM" },
  { name: "Sony", ticker: "SONY" },
  { name: "Samsung Electronics", ticker: "005930.KS" },
  { name: "Alibaba", ticker: "BABA" },
  { name: "Tencent", ticker: "0700.HK" },
  { name: "JD.com", ticker: "JD" },
  { name: "Baidu", ticker: "BIDU" },
  { name: "Toyota Motor", ticker: "TM" },
  { name: "Honda Motor", ticker: "HMC" },
  { name: "Nintendo", ticker: "NTDOY" },
  { name: "Rivian", ticker: "RIVN" },
  { name: "Lucid Motors", ticker: "LCID" },
  { name: "Roblox", ticker: "RBLX" },
  { name: "Coinbase", ticker: "COIN" },
  { name: "MicroStrategy (Strategy)", ticker: "MSTR" },
  { name: "Block (Square)", ticker: "SQ" },
  { name: "Affirm", ticker: "AFRM" },
  { name: "Robinhood", ticker: "HOOD" },
  { name: "SoFi Technologies", ticker: "SOFI" },
  { name: "Datadog", ticker: "DDOG" },
  { name: "CrowdStrike", ticker: "CRWD" },
  { name: "Palo Alto Networks", ticker: "PANW" },
  { name: "Fortinet", ticker: "FTNT" },
  { name: "Zscaler", ticker: "ZS" },
  { name: "Cloudflare", ticker: "NET" },
  { name: "MongoDB", ticker: "MDB" },
  { name: "Atlassian", ticker: "TEAM" },
  { name: "Workday", ticker: "WDAY" },
  { name: "Intuit", ticker: "INTU" },
  { name: "Airbus", ticker: "AIR.PA" },
  { name: "LVMH", ticker: "MC.PA" },
  { name: "L'Oréal", ticker: "OR.PA" },
  { name: "TotalEnergies", ticker: "TTE" },
  { name: "Sanofi", ticker: "SNY" },
  { name: "BNP Paribas", ticker: "BNP.PA" },
  { name: "Siemens", ticker: "SIE.DE" },
  { name: "SAP", ticker: "SAP" },
  { name: "Volkswagen", ticker: "VOW3.DE" },
  { name: "BMW", ticker: "BMW.DE" },
  { name: "Mercedes-Benz Group", ticker: "MBG.DE" },
  { name: "Allianz", ticker: "ALV.DE" },
  { name: "Deutsche Bank", ticker: "DB" },
  { name: "Novo Nordisk", ticker: "NVO" },
  { name: "Nestlé", ticker: "NESN.SW" },
  { name: "Roche", ticker: "RHHBY" },
  { name: "Novartis", ticker: "NVS" },
  { name: "UBS Group", ticker: "UBS" },
  { name: "Shell", ticker: "SHEL" },
  { name: "BP", ticker: "BP" },
  { name: "AstraZeneca", ticker: "AZN" },
  { name: "GSK", ticker: "GSK" },
  { name: "HSBC", ticker: "HSBC" },
  { name: "Unilever", ticker: "UL" },
  { name: "Diageo", ticker: "DEO" },
  { name: "Rolls-Royce", ticker: "RR.L" },
  { name: "BAE Systems", ticker: "BA.L" },
  { name: "Banco Santander", ticker: "SAN" },
  { name: "BBVA", ticker: "BBVA" },
  { name: "Inditex (Zara)", ticker: "ITX.MC" },
  { name: "Iberdrola", ticker: "IBE.MC" },
  { name: "Repsol", ticker: "REP.MC" },
  { name: "Telefónica", ticker: "TEF" },
  { name: "CaixaBank", ticker: "CABK.MC" },
  { name: "Ferrovial", ticker: "FER.MC" },
  { name: "Naturgy", ticker: "NTGY.MC" },
  { name: "Mapfre", ticker: "MAP.MC" },
  { name: "Endesa", ticker: "ELE.MC" },
  { name: "Grifols", ticker: "GRF.MC" },
  { name: "Cellnex Telecom", ticker: "CLNX.MC" },
  { name: "Amadeus IT Group", ticker: "AMS.MC" },
  { name: "Aena", ticker: "AENA.MC" },
  { name: "ArcelorMittal", ticker: "MT" },
  { name: "Ferrari", ticker: "RACE" },
  { name: "Stellantis", ticker: "STLA" },
  { name: "Intesa Sanpaolo", ticker: "ISP.MI" },
  { name: "UniCredit", ticker: "UCG.MI" },
  { name: "Enel", ticker: "ENEL.MI" },
  { name: "Eni", ticker: "ENI.MI" },
  { name: "Moderna", ticker: "MRNA" },
  { name: "Pfizer", ticker: "PFE" },
  { name: "Merck", ticker: "MRK" },
  { name: "Bristol Myers Squibb", ticker: "BMY" },
  { name: "Amgen", ticker: "AMGN" },
  { name: "Gilead Sciences", ticker: "GILD" },
  { name: "CVS Health", ticker: "CVS" },
  { name: "Walgreens Boots Alliance", ticker: "WBA" },
  { name: "Target", ticker: "TGT" },
  { name: "Lowe's", ticker: "LOW" },
  { name: "TJX Companies", ticker: "TJX" },
  { name: "Estée Lauder", ticker: "EL" },
  { name: "Colgate-Palmolive", ticker: "CL" },
  { name: "Kimberly-Clark", ticker: "KMB" },
  { name: "General Electric", ticker: "GE" },
  { name: "Lockheed Martin", ticker: "LMT" },
  { name: "Northrop Grumman", ticker: "NOC" },
  { name: "RTX (Raytheon)", ticker: "RTX" },
  { name: "Deere & Company", ticker: "DE" },
  { name: "Union Pacific", ticker: "UNP" },
  { name: "Southwest Airlines", ticker: "LUV" },
  { name: "Delta Air Lines", ticker: "DAL" },
  { name: "American Airlines", ticker: "AAL" },
  { name: "United Airlines", ticker: "UAL" },
  { name: "Marriott International", ticker: "MAR" },
  { name: "Hilton Worldwide", ticker: "HLT" },
  { name: "Yum! Brands", ticker: "YUM" },
  { name: "Chipotle Mexican Grill", ticker: "CMG" },
  { name: "Domino's Pizza", ticker: "DPZ" },
  { name: "DoorDash", ticker: "DASH" },
  { name: "Take-Two Interactive", ticker: "TTWO" },
  { name: "Electronic Arts", ticker: "EA" },
  { name: "Activision Blizzard", ticker: "ATVI" },
  { name: "Warner Bros. Discovery", ticker: "WBD" },
  { name: "Paramount Global", ticker: "PARA" },
  { name: "Charles Schwab", ticker: "SCHW" },
  { name: "BlackRock", ticker: "BLK" },
  { name: "American Express", ticker: "AXP" },
  { name: "Wells Fargo", ticker: "WFC" },
  { name: "Citigroup", ticker: "C" },
  { name: "US Bancorp", ticker: "USB" },
  { name: "S&P Global", ticker: "SPGI" },
  { name: "Moody's", ticker: "MCO" },
  { name: "CME Group", ticker: "CME" },
  { name: "Intercontinental Exchange", ticker: "ICE" },
  { name: "Dell Technologies", ticker: "DELL" },
  { name: "HP", ticker: "HPQ" },
  { name: "Western Digital", ticker: "WDC" },
  { name: "Seagate Technology", ticker: "STX" },
  { name: "Corning", ticker: "GLW" },
  { name: "Xerox", ticker: "XRX" },
  { name: "Snap", ticker: "SNAP" },
  { name: "Pinterest", ticker: "PINS" },
  { name: "Reddit", ticker: "RDDT" },
  { name: "Twilio", ticker: "TWLO" },
  { name: "Zoom Video Communications", ticker: "ZM" },
  { name: "DocuSign", ticker: "DOCU" },
  { name: "Dropbox", ticker: "DBX" },
  { name: "Etsy", ticker: "ETSY" },
];
